#!/bin/bash

BOX_NW=$'\u250C'
BOX_NE=$'\u2510'
BOX_SW=$'\u2514'
BOX_SE=$'\u2518'
BOX_HO=$'\u2500'
BOX_VE=$'\u2502'

get-date()
{
    date +"%H:%M:%S %Z %a %d/%m/%Y"
}

bar()
{
    local bar_char
    if [ "$#" -eq 2 ]; then
	bar_char="$2"
    else
	bar_char="$BOX_HO"
    fi

    for ((i=0; i<${#1}; i++)); do
        printf "%s" "$bar_char"
    done
}

february-days()
{
    year=$(date +%Y)
    if (( (year % 4 == 0 && year % 100 != 0) || year % 400 == 0 )); then
        echo "29"
    else
        echo "28"
    fi
}

days-in-month()
{
    local days
    case $1 in
    01|03|05|07|08|10|12) days=31 ;;
    04|06|09|11)          days=30 ;;
    02)                   days=28 ;;
    *)                    days=$(february-days) ;;
    esac
    echo $days
}

first-of-month()
{
    date -d "$(date +%Y)-$1-01" +%u
}

calendar()
{
    local cur_date
    local calendar_date_str="%m %_B %Y %-d"
    if [ "$#" -eq 0 ]; then
        cur_date="$(date +"$calendar_date_str")"
    else
        if [ "$1" = "-d" ]; then
            echo "$calendar_date_str"
            return
        else
            cur_date="$1"
        fi
    fi
    local cur_month=$(echo "$cur_date" | awk '{print $1}')
    local header=$(echo "$cur_date" | awk '{print $2, $3}')
    local today=$(echo "$cur_date" | awk '{print $4}')
    local fotm=$(first-of-month $cur_month)
    local days=$(($(days-in-month $cur_month)+$fotm))

    printf "    %9s\n" "$header"
    echo "--------------------"
    echo " S  M  T  W  T  F  S"

    local start
    if [ $fotm -eq 7 ]; then
        start=8
    else
        start=1
    fi
    for ((d=$start; d<=$days; d++)); do
        if [ $d -le $fotm ]; then
            printf "  "
        else
	    printf "%2d" "$(($d-$fotm))" 
        fi
        if [ $d -eq $days ]; then
            break
        fi
        if [ $(($d%7)) -eq 0 ]; then
            printf "\n"
        else
            printf " "
        fi
    done
    printf "\n"
}

box()
{
    temp="$1.tmp"
    cat "$@" >"$temp"
    longest_line=$(awk 'length > max { max = length; longest = $0 } END { printf longest }' "$temp")
    echo "$BOX_NW$BOX_HO$(bar "$longest_line")$BOX_HO$BOX_NE"
    line_box="$BOX_VE $(bar "$longest_line" " ") $BOX_VE"
    line_undo="$(bar "  $longest_line" $'\b')"
    awk -v v1="$line_box" -v v2="$line_undo" '{printf "%s%s%s\n", v1, v2, $0 }' "$temp"
    echo "$BOX_SW$BOX_HO$(bar "$longest_line")$BOX_HO$BOX_SE"
    rm "$temp"
}

draw-hud()
{
    clear
    get-date | box
    calendar | box
}

hud()
{
    stty -echo
    printf "\033[?25l"

    draw-hud

    local last_d=$(date +%d)
    while true
    do
        read -t 0.1 -n 1 key
        if [[ $key ]]; then
            clear
            stty echo
            printf "\033[?25h"
            break
        fi

        printf "\033[2;3H$(get-date)"
        if [ "$(date +%d)" -ne "$last_d" ]; then
            draw-hud
	fi
        last_d=$(date +%d)
        sleep 0.1
    done
    printf "\033[?25h"
}
