#!/bin/bash

BOX_NW=$'\u250C'
BOX_NE=$'\u2510'
BOX_SW=$'\u2514'
BOX_SE=$'\u2518'
BOX_HO=$'\u2500'
BOX_VE=$'\u2502'

get_date()
{
    date +"%H:%M:%S %Z %d/%m/%Y %A"
}

bar()
{
    for ((i=0; i<${#1}; i++)); do
        echo -n "$BOX_HO"
    done
}

hud()
{
    clear
    local cur_date=$(get_date)
    echo "$BOX_NW$BOX_HO$(bar "$cur_date")$BOX_HO$BOX_NE"
    echo "$BOX_VE $cur_date $BOX_VE"
    echo "$BOX_SW$BOX_HO$(bar "$cur_date")$BOX_HO$BOX_SE"

    while true
        do
        cur_date=$(get_date)
        printf "\033[2;3H$cur_date"
        sleep 1
    done
}
